spring:
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 30000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
legacy:
  base-url: https://65bce235b51f9b29e9327d3d.mockapi.io
