version: '3.5'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    container_name: postgres
    volumes:
      - appdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - '6379:6379'

volumes:
  appdata:
